### ISSUE TITLE
PD Runner doesn't show up in the menu bar

### ISSUE THREAD

**Issue by binhprodotcom** [lihaoyun6/PD-Runner#162]
The application does not show up in the menubar, when I open it, I only get the message like the picture. Please support. Thank you

![This is an image](https://i.imgur.com/wYiN3Mb.png)

**Comment by Mr-Sheep** [comment]
Hey @binhprodotcom, you **have to regiester an parallels account** using the Parallels Desktop app first. Then you can fire up PD Runner.

**Comment by lihaoyun6** [comment]
@binhprodotcom 
Just like the literal meaning of this message. You need to log in to your Parallels Desktop account first, and get a 14-day free trial. This will give you a license, and PD Runner needs it.
What PD Runner does is to make Parallels Desktop trust your existing license unconditionally, instead of creating it out of nothing.
