### ISSUE TITLE
Translating app into other languages

### ISSUE THREAD

**Issue by rakleed** [lihaoyun6/PD-Runner#83]
Could you please provide the community with the ability to translate the app into other languages?

P.S. I can help with translation into Russian.

**Comment by lihaoyun6** [comment]
> Could you please provide the community with the ability to translate the app into other languages?
> 
> P.S. I can help with translation into Russian.

This sounds great!
And I have uploaded a string file (in the "localization" folder).
You can use this file to create translations in other languages.

**Comment by rakleed** [comment]
@lihaoyun6 could you provide some context for these strings? Since I didn't see them when using the app.
- "is encrypted"
- "User cancelled"
- "Nothing will change."
- "Nothing will be changed."

I also saw some lines in the application that are not in your file. Here are screenshots:
<details><summary>Screenshots</summary>


![screenshot1](https://user-images.githubusercontent.com/19418601/143722292-7f083c55-a2e0-415e-9845-e17932856475.png) ![screenshot2](https://user-images.githubusercontent.com/19418601/143722294-0f9451c7-9c8b-4bad-8a9d-90130065e985.png) ![screenshot3](https://user-images.githubusercontent.com/19418601/143722295-f0fcb54a-4154-4fd7-b980-489caa24a2fa.png)

</details>

Can you add them to the strings file as well?

**Comment by lihaoyun6** [comment]
> 

**"Switch now?"** has changed. Now it's called "Restore now?" in the string file. (this string will be updated in the next version)
**"is encrypted"** is part of the dialog when an encrypted VM is starting(like "Windows 11 is encrypted")
**"Nothing will change."** is a mistake, and now it will be called **"The requested operation has been cancelled."** (this string will be updated in the next version)
Thank you for your reminder. I will update the template file later and explain the meaning of some lines.

There are also some lines that are not in the file. Because I don't want someone to modify them (then pretend that PD Runner is their work and sell it for money). So they are encrypted and not stored in a string file. 
However, these "warnings" will be removed in future versions (except "zh-Hans" and "zh-Hant"). So I don't think it's necessary to translate them.

**Comment by lihaoyun6** [comment]
@rakleed 
I have updated the string file. Now you can proofread your translation again. Thank you for your support!

**Comment by rakleed** [comment]
@lihaoyun6 done: https://github.com/rakleed/PD-Runner/blob/main/localization/ru.strings

I would do a PR, but it’s probably worth testing first so that everything is displayed correctly. Can you build an app with my translation and post it here?

> There are also some lines that are not in the file. Because I don't want someone to modify them (then pretend that PD Runner is their work and sell it for money). So they are encrypted and not stored in a string file.
However, these "warnings" will be removed in future versions (except "zh-Hans" and "zh-Hant"). So I don't think it's necessary to translate them.

But the information from About would be nice to translate. Is there no way for me to translate it, and then you encrypted it when building the app? Or won't it work that way?

**Comment by lihaoyun6** [comment]
> 

about the information from "About Panel", you can put it directly into the string file (as comments), and I will use them

**Comment by lihaoyun6** [comment]
@rakleed 
[PD Runner.app.zip](https://github.com/lihaoyun6/PD-Runner/files/7613549/PD.Runner.app.zip)

**Comment by rakleed** [comment]
@lihaoyun6 slightly improved the translation, corrected typos and added a translation for About at the very end (and also added a translation for the author and copyright): https://github.com/rakleed/PD-Runner/blob/main/localization/ru.strings

While using the app, I did not notice any problems due to the translation.

Unless, for some reason, the “Cancel” button was not localized in the pop-up window with a confirmation for restoring the snapshot, although it was translated in another pop-up window with a request to enter the password for the VM.
<details><summary>Screenshot</summary>

![Снимок экрана 2021-11-28 в 21 24 16](https://user-images.githubusercontent.com/19418601/143782411-0a233a9f-da56-4d47-bc1c-a2865e196432.png)

</details>

And there is a question about line 35 with "Nothing will be changed." Why is the future tense used, if the user has already clicked Cancel? And accordingly, the action has already taken place, and this is just informing. I think "Nothing has changed" is better suited in this case.

**Comment by lihaoyun6** [comment]
> 

Thank you. I have fixed two problems you found. Now version 0.2.9 has been released.
It includes the Russian translation you provided and the link to your GitHub home page.

<details><summary>Screenshot</summary>

<img width="272" alt="Xnip2021-11-29_13-40-40" src="https://user-images.githubusercontent.com/16348097/143815527-741959bf-cf0e-4445-80e9-9e821b2ce369.png">

</details>

**Comment by rakleed** [comment]
@lihaoyun6 nice! And why did you decide not to translate information about the copyright?

**Comment by lihaoyun6** [comment]
@rakleed 
OK, I've fixed this line. 
For the Info.plist, I use a script to modify it automatically. If I want to localize the Info.plist, I need to make a lot of changes to the script. So I decided to devote more energy to the code rather than copyright string.
Thank you again for your contribution, but I'm not going to localize the copyright string for the time being.

**Comment by rakleed** [comment]
I also updated the translation for line 35, and made the structure of the lines the same as in https://github.com/lihaoyun6/PD-Runner/blob/main/localization/base.strings: https://github.com/lihaoyun6/PD-Runner/pull/85

**Comment by rakleed** [comment]
@lihaoyun6 and in the next version use the current Russian translation https://github.com/lihaoyun6/PD-Runner/blob/main/localization/ru.strings, since at some point I changed the 2nd line, but in https://github.com/lihaoyun6/PD-Runner/releases/tag/0.2.10 still its old translation.

**Comment by rakleed** [comment]
@lihaoyun6 ping
